# Generated by Django 6.0.5 on 2026-05-16 16:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_booking_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel__name', 'room_number']},
        ),
        migrations.RenameIndex(
            model_name='room',
            new_name='rooms_hotel_i_fc2043_idx',
            old_name='rooms_hotel_id_idx',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
