# Generated by Django 6.0.4 on 2026-04-24 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('identification_number', models.CharField(blank=True, help_text='Passport or ID number', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guests',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='guests_last_na_352172_idx'), models.Index(fields=['email'], name='guests_email_a33f61_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When guest entered premises')),
                ('exit_time', models.DateTimeField(blank=True, help_text='When guest left premises (NULL = still present)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_logs', to='visitor.guest')),
                ('processed_by', models.ForeignKey(help_text='Concierge who processed this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_visits', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Room assignment during visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='inventory.room')),
            ],
            options={
                'db_table': 'visit_logs',
                'ordering': ['-entry_time'],
                'indexes': [models.Index(fields=['entry_time'], name='visit_logs_entry_t_58b843_idx'), models.Index(fields=['exit_time'], name='visit_logs_exit_ti_724c88_idx'), models.Index(fields=['-entry_time'], name='visit_logs_entry_t_dbd036_idx')],
            },
        ),
    ]
